services:
  - type: web
    name: estella-wilson-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://realestate-analysis.netlify.app
